spring:
  profiles:
    active: production

proxy:
  cmdb:
    servlet_url: /cmdb/*
    target_url: http://indigo.cloud.plgrid.pl/cmdb
  cmdb-crud:
    servlet_url: /cmdb-crud/*
    target_url: http://couch.cloud.plgrid.pl/indigo-cmdb-v2
    # username: XXX
    # password: XXX

oidc:
  userinfo: https://iam-test.indigo-datacloud.eu/userinfo
